theme = "ayu_evolve"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
S-n = "extend_search_next"
C-t = "file_picker"
# G = ["select_mode", "g"]
C-r = ":sh 'alacritty'"

[keys.insert]
C-n = "completion"

[keys.normal.g]
j = "goto_file_end"
k = "goto_file_start"


# formatters


